Repository PritamMaharjan86/Recipe-app, pull requests merged in 2024-04, with the labels that each got.

#7 package
  package-lock.json
  package.json
  src/App.js
Labels: feature

#9 feature/UI
  package-lock.json
  package.json
  src/App.css
  src/App.js
Labels: feature

#30 feature/10/loader
  src/App.css
  src/App.js
  src/components/loader.js
Labels: feature, frontend

#33 feature/UI/css
  src/App.css
  src/App.js
Labels: feature, frontend

#38 Feature/11/login register screen
  .DS_Store
  .vscode/settings.json
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/components/register.js
  client/src/index.css
  client/src/index.js
  client/src/logo.svg
  client/src/pages/home.css
  client/src/pages/home.js
  client/src/pages/login.css
  client/src/pages/login.js
  client/src/reportWebVitals.js
  client/src/routes/route.js
  client/src/setupTests.js
Labels: feature, frontend

#41 feature/11/loginUI
  client/src/pages/login.css
  client/src/pages/login.js
Labels: feature, frontend

#42 pino logger added #32
  server/package-lock.json
  server/package.json
  server/src/index.js
  server/src/logger.js
  server/src/middleware/loggerMiddleware.js
Labels: backend

#43 login screen and auth
  client/.env
  client/package-lock.json
  client/package.json
  client/src/config.js
  client/src/index.css
  client/src/pages/http.js
  client/src/pages/login.css
  client/src/pages/login.js
  client/src/routes/privateRoute.js
  client/src/routes/route.js
Labels: feature, backend

#48 feature/44/logout-button/css
  client/src/pages/home.css
  client/src/pages/home.js
Labels: feature, frontend

#50 feature/49/toast-notification-added
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/pages/home.css
  client/src/pages/home.js
  client/src/pages/login.css
  client/src/pages/login.js
  client/src/routes/privateRoute.js
  client/src/routes/route.js
  client/yarn.lock
Labels: feature, frontend

#51 feature/14/register.js added
  client/src/pages/login.css
  client/src/pages/login.js
  client/src/pages/register.css
  client/src/pages/register.js
  client/src/routes/route.js
Labels: frontend

#57 feature/14/register/UI
  client/src/pages/register.css
  client/src/pages/register.js
Labels: feature, frontend
