Repository PritamMaharjan86/Recipe-app, pull requests merged in 2024-05, with the labels that each got.

#60 update-user API supports password change #59
  server/src/routes/user.js
  server/src/services/user.js
Labels: backend

#61 Feature/19/edit/user/profile
  .DS_Store
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/pages/home.css
  client/src/pages/home.js
  client/src/pages/profile.js
  client/src/pages/register.js
  client/yarn.lock
  server/src/middleware/tokenValidator.js
  server/src/services/auth.js
  server/src/services/user.js
Labels: feature, frontend, backend

#62 add comment API added #26
  server/src/controllers/recipe/index.js
  server/src/routes/recipe.js
  server/src/services/recipe.js
  server/src/sqls/changed.sql
  server/src/swagger.json
Labels: backend

#63 Feature/19/edit/user/profile
  client/src/pages/home.js
  client/src/pages/profile.js
  server/src/controllers/recipe/index.js
  server/src/routes/recipe.js
  server/src/services/recipe.js
  server/src/swagger.json
Labels: feature, frontend, backend

#64 Feature/24/comment/recipe
  client/src/components/comment.css
  client/src/components/comment.js
  client/src/pages/home.js
  client/src/routes/route.js
Labels: backend

#65 Like API added
  server/src/controllers/recipe/index.js
  server/src/routes/recipe.js
  server/src/services/recipe.js
  server/src/sqls/changed.sql
  server/src/swagger.json
Labels: backend

#67 get-all-recipe api updated #66
  server/src/services/recipe.js
Labels: backend

#68 Feature/24/comment/recipe
  client/src/components/comment.js
  client/src/pages/home.js
  client/src/pages/login.js
  server/src/routes/user.js
  server/src/services/recipe.js
Labels: frontend, backend

#73 Feature/25/like/recipe
  client/src/components/comment.css
  client/src/components/comment.js
  client/src/pages/home.css
  client/src/pages/home.js
  server/src/services/recipe.js
Labels: frontend, backend

#77 feature/75/email-added
  client/src/pages/home.js
  client/src/pages/register.css
  client/src/pages/register.js
Labels: feature, frontend, backend

#82 Feature/52/email verification
  server/src/services/auth.js
  server/src/sqls/changed.sql
  server/src/swagger.json
Labels: feature, backend

#83 feature/76/added-validation
  client/src/pages/register.js
Labels: feature, frontend
